### ISSUE TITLE
Долгосрочные планы развития сети «Medium»

### ISSUE THREAD

**Issue by podivilov** [medium-isp/medium#1]

**Comment by datsenko** [comment]
Наверное это интересно и полезно. Нужно будет уделить это внимание да разобраться, что да к чему.
а так Вам ЛАЙК ! )

**Comment by ivan386** [comment]
> Можно использовать два SSID. Первый («Medium») оставить открытым и пользователи кому не настолько важна приватность могут подключатся и к нему. А второй («MediumEncrypted») будет под общим паролем. Те кому важна приватность будут подключаться только ко второму. Остальные пользователи могут подключатся ко всем.

**Comment by podivilov** [comment]
А что насчёт грядущего стандарта WPA3?

**Comment by ivan386** [comment]
Как выйдет можно будет использовать и его.

**Comment by podivilov** [comment]
Мне думается, что использование OpenPGP нивелирует все проблемы с безопасностью в принципе. Medium предоставляет транспорт для передачи данных по сети, а не приватность "из коробки". Об этом должен уже похлопотать сам пользователь. По крайней мере, это моё личное видение данной проблемы. Было бы здорово обсудить её прочие нюансы.

**Comment by ivan386** [comment]
А OpenPGP куда будет потключаться? Как быть с сайтами в i2p?

**Comment by podivilov** [comment]
Можно поднять свой SKS для OpenPGP в сети I2P. Например, sks-keyserver.medium.i2p.

**Comment by ivan386** [comment]
Пусть OpenPGP так же будет дополнительной опцией для пользователей.

С шифрованной и не шифрованной точкой операторы точек и пользователи будут иметь выбор уровня безопасности. Если сеть будет безальтернативно открытой то это будет перевёрнутый ТОР. Только у ТОРа трафик не шифрованный на том конце а клиент на этом. У Медиума же и не шифрованный трафик и клиент на этом конце и делай с ним что хочешь.

**Comment by podivilov** [comment]
Вообще, мысль здравая — но нужно обдумать все важные технические нюансы реализации. Чтобы после не вскрылось, что не хватает чего-то ещё.

**Comment by LainTech** [comment]
Боюсь, вся затея упирается в одно. Даже если трафик от клиента до точки идёт по зашифрованному каналу, то он до попадания в i2p тоннель открыт на стороне сервера. 
Речь идёт о доверии Чертову Ублюдку Оператору. По-хорошему, точка должна быть транзитной, а трафик заворачиваться на стороне клиента.

**Comment by podivilov** [comment]
@LainTech Ваши опасения мне в достаточной степени понятны — и это естественно: однако давайте же не будем забывать про то, что мы и так считаем, что по умолчанию сеть скомпрометирована и клиент должен сам позаботиться о своей безопасности. Я говорю об OpenPGP и TLS. Medium предоставляет транспорт для передачи данных и способствует развитию сети I2P.

Операторы мы не доверяем. Выходные ноды тора, к слову, обладают такой же проблемой. В случае с Медиумом проблема со входной нодой — то есть, грубо говоря, наоборот. Если это несколько переиначить, то получится следующее: обычный HTTP-трафик можно подменять на стороне exit-ноды тора, равно как и его можно подменять со стороны оператора Medium. А в случае использования HTTPS такая проблема исчезает. stats.i2p, к слову, поддерживает HTTPS. В случае непосредственного использования транспорта I2P без Medium нет никакой нужды в HTTPS — об этом говорится и в официальном руководстве, однако же в нашей ситуации смысл есть.

**Comment by podivilov** [comment]
@LainTech, трафик теперь шифруется посредством использования HTTPS.

**Comment by mike-lambert** [comment]
У меня есть прототип анонимизирующего WLAN-роутера на базе Raspberry Pi, использующего Tor, а также умеющего в аппаратную индикацию статуса. Это необслуживаемое решение (прожёг образ на карточку, подал питание и канал, и забыл).
Для беспроводных клиентов, соответственно доступны .onion домены "из коробки".

Могу подготовить аналогичный образ с I2PD.

**Comment by podivilov** [comment]
@mike-lambert, это было бы очень кстати.

Проблема в том, что зоопарк моделей Raspberry Pi за последнее время заметно вырос. Для разных моделей с разным количеством оперативной памяти нужен отличный от других образ. Как Вы хотите решить эту проблему?

**Comment by mike-lambert** [comment]
@podivilov не так уж он сильно и вырос.
Pi 1/Pi 2 не рассматриваем ввиду их морального устаревания
Pi 4 пока сырой (греется в частности).

Так что мейнстримной моделью остается Pi 3B.
Zero W может работать только как мобильный роутер ввиду отсутствия Ethernet-порта, но менять под нее образ не нужно.

В качестве базового образа выступает унифицированный Raspbian Lite (без графического интерфейса).
Поверх него штатным apt накатываются необходимые пакеты.
Остается минимум в виде конфигов и скриптов из репозитория [RPMH](https://github.com/mike-lambert/raspberrypi-management-hat). И такой образ заведется и на Zero W, и на 3B.
AFAIK, под RPi есть нативный i2pd, это должно облегчить задачу.

На выходе имеем образ, который легко эксплуатируем неквалифицированным волонтером, и для базовой диагностики и обслуживания достаточно невооруженного глаза (шилд с кнопками, светодиодами).

**Comment by podivilov** [comment]
@mike-lambert, получается, малинка цепляется за Ethernet, а на выходе мы получаем скрытую Wi-Fi сетку с SSID "Medium". Если я всё правильно понимаю.

**Comment by mike-lambert** [comment]
Да, совершенно верно. При отвале аплинка, мониторинговый сервис останавливает демона анонимизации, при поднятии - перезапускает.

Что касается WLAN - можно скрытую, можно анонсируемую (в моем анонироутере - анонсируемая с SSID "TorAccess" с фиксированным паролем) - это все настраивается в конфиге hostapd.

**Comment by podivilov** [comment]
@mike-lambert, пока что мы используем скрытую сеть без пароля, так как считаем, что все промежуточные узлы между пользователем, оператором и оператором сервиса скомпрометированы.

Я Вас [пригласил](https://github.com/medium-isp/medium-raspberry-pi/invitations) в новый репозиторий medium-raspberry-pi как коллаборатора.

**Comment by mike-lambert** [comment]
@podivilov хорошо.
примерный срок до MVP - середина августа, я сейчас несколько загружен.

**Comment by podivilov** [comment]
@mike-lambert, желаю успехов!

**Comment by podivilov** [comment]
Medium полностью перешёл на Yggdrasil.

**Comment by EAnsy** [comment]
Есть немаленькая вероятность, что WPA-шифрование необходимо технологически. Радиоточки Wi-Fi 802.11n (возможно не все, читал где-то у Ubiquiti) ограничивают клиентов без шифрования низкими уровнями модуляции и скоростями.
P.S. https://en.wikipedia.org/wiki/Wi-Fi_Protected_Access
> According to the 802.11n specification, this encryption protocol must be used to achieve fast 802.11n high bitrate schemes, though not all implementations[vague] enforce this.[20] Otherwise, the data rate will not exceed 54 Mbit/s

**Comment by podivilov** [comment]
@EAnsy, добрый день!

Мы используем 802.11s. Распространяется ли на эти радиоточки ограничение, которое Вы привели в пример?

**Comment by EAnsy** [comment]
> @EAnsy, добрый день!
> 
> Мы используем 802.11s. Распространяется ли на эти радиоточки ограничение, которое Вы привели в пример?

Насколь я понял из документации, в том месте сети, применительно к которому вами обсуждается открытость/зашифрованность канала связи, стандарт 802.11s не применим, т.е. между конечным клиентом и ближайшей точкой беспроводного доступа связь устанавливается по распространённым протоколам 802.11a/b/g/n/ac с необходимыми им механизмами шифрования:
https://www.cwnp.com/wp-content/uploads/pdf/802.11s_mesh_networking_v1.0.pdf
> Because mesh networks are different from traditional wireless networks, the 802.11s amendment changes the name and functionality of several wireless infrastructure components. Nothing needs to change on the wireless client station (non-AP client device, such as a laptop or VoWLAN phone) side. A wireless client can still associate to an access point’s BSS normally, without needing to know if the access point connects to the wired network directly (standard AP) or through a mesh cloud (mesh AP). In Figure 2, client stations H, I, K, L N, O, Q, and R do not need any specific 802.11s functionality to connect to their respective access points.

**Comment by podivilov** [comment]
Обсуждения переехали на [discuss.mediumfoundation.org](https://discuss.mediumfoundation.org/).
