### ISSUE TITLE
Разработать форк OpenWRT с i2pd на борту для быстрого развёртывания точек сети «Medium»

### ISSUE THREAD

**Issue by podivilov** [medium-isp/medium#14]

**Comment by podivilov** [comment]
https://github.com/medium-isp/medium-openwrt

**Comment by podivilov** [comment]
deprecated

**Comment by skywinder** [comment]
почему закрыта?
есть решение вместо этого? идея с прошивкой для роутера звучит логично

**Comment by podivilov** [comment]
@skywinder, мы на Yggdrasil перешли. Вы можете открыть новый тикет для Yggdrasil.
