### ISSUE TITLE
Взгляд на сеть «Medium» со стороны юрисдикции РФ

### ISSUE THREAD

**Issue by podivilov** [medium-isp/medium#17]

**Comment by xN0D** [comment]
Если Вы называете себя провайдером на территории РФ, не влечет ли это за собой обязанность обязательного внедрения СОРМ и пакета Яровой?

**Comment by podivilov** [comment]
@xN0D, а как Вы себе это представляете?

**Comment by xN0D** [comment]
Я это себе представляю так, Вы(сеть Medium) работаете до тех пор пока не обратите на себя внимание компетентных органов. После чего последуют "вызовы" к следователю для пояснения ситуации. Вычислять узлы особенно не придется, они перечислены в Ваших списках, найти конкретного владельца узла - тоже. Запротоколируют нарушение законодательства в сфере связи и коммуникаций, как раз по СОРМу и пакету Яровой, и впаяют каждому неадекватный штраф.

**Comment by podivilov** [comment]
Мне не совсем понятно, о каком нарушении "закона о связи" Вы говорите в предыдущем своём сообщении. Вы можете привести конкретный пример из свода законов РФ?

**Comment by xN0D** [comment]
https://77.rkn.gov.ru/p5275/p17834/p18148/

**Comment by podivilov** [comment]
Вы не совсем правы с юридической точки зрения. «Medium» де-юре не относится к операторам связи ввиду того, что сеть работает на добровольных началах и как юридическое лицо не зарегистрировано. Соответственно, «Medium» не является лицензиатом. Поэтому к нему нельзя применить правила, которые распространяются на оператор.

> Оператор связи — юридическое лицо или индивидуальный предприниматель, оказывающие услуги связи на основании соответствующей лицензии.

**Comment by xN0D** [comment]
> «Medium» де-юре не относится к операторам связи ввиду того, что сеть работает на добровольных началах и как юридическое лицо не зарегистрирован.

Это Ваша главная ошибка, отсутствие регистрации ЮЛ и добровольные начала не дают права заниматься на территории РФ лицензируемыми видами деятельности без получения соответстующей лицензии. Иначе этой лазейкой пользовались бы все.

Все это, всего лишь, мое мнение. Но это можно проверить на практике.

Вы можете самостоятельно провести, так сказать, правовой аудит своей сети.
Нужно всего лишь самому написать официальное письмо в Роскомнадзор с просьбой дать правовую оценку деятельности сети Medium.
Варианта развития событий ровно два:
1. Роскомнадзор не находит в Вашей деятельности ничего противозаконного, и высылает на Ваш адрес официальный ответ, в котором это и сообщает.
2. Роскомнадзор находит в Вашей деятельности нарушения и начинаются гонения, кары, и репрессии описанные мною выше.
В обоих случаях у Вас будет компетентное заключение о законности Ваших действий.
А в данный момент Вы действуете на принципе "Неуловимого Джо" и поэтому коль нибудь серьезной поддержки, для развития, получить не сможете.

**Comment by xN0D** [comment]
А еще есть любопытный законопроект о WiFi
https://regulation.gov.ru/projects#npa=27123

**Comment by podivilov** [comment]
Мне не совсем понятно, почему Вы считаете, что отсутствие наличия лицензии у физического лица запрещает ему оказывать безвозмездные услуги связи другим физическим лицам.

> Иначе этой лазейкой пользовались бы все.

Вы говорите про сценарий, когда какая-нибудь компания а-ля Ростелеком создавала бы НКО для оказания услуг связи? Но позвольте, даже здесь это же не безвозмездное оказание услуг связи. Это юридическое лицо, следовательно, и действовать оно должно согласно с юрисдикцией РФ.

Никто не лицензирует себя как оператора связи, когда, грубо говоря, делится с соседями своим Wi-Fi. Это вздор.

**Comment by podivilov** [comment]
> А еще есть любопытный законопроект о WiFi

> Предоставление безвозмездного доступа к информационно-телекоммуникационной сети «Интернет» в общественных местах абонентом – юридическим лицом [...]

**Comment by xN0D** [comment]
Кстати, есть такой ресурс РосКомСвобода, Вы с ними консультировались? Там у них много судебной практики. Они могли бы сделать предварительное заключение о правомерности использования. Все лучше чем ничего.

**Comment by podivilov** [comment]
Спасибо за ценное предложение. Мы обязательно проконсультируемся с РосКомСвободой. Отпишусь по результатам в этой же ветке.

**Comment by xN0D** [comment]
Вот еще интересный комментарий от Роскомнадзора: https://news.softodrom.ru/ap/b29762.shtml

> Если ваш энтузиазм не угас и вы хотите использовать мощный роутер , чтобы раздавать Wi-Fi на большой площади, то придется пройти все разрешительные процедуры. Это делается для того, что ваш передатчик не создал помех другим радиоэлектронным устройствам. В числе этих процедур - получение в Роскомнадзоре разрешения на использование радиочастот и регистрация вашего роутера в территориальном управлении Роскомнадзора.
> 
> Раздача Wi-Fi на большой территории – это оказание услуг связи. А эта деятельность в России подлежит лицензированию.
> 
> Подробнее с порядком лицензирования можно ознакомиться здесь:
> https://rkn.gov.ru/communication/licensing-activity/
> https://rkn.gov.ru/communication/license/

**Comment by podivilov** [comment]
> Update:
> Читайте, пожалуйста, внимательней. Речь не идет о законности-незаконности раздачи Wi-Fi на одну-несколько квартир. Мы просто предположили, что мощности сигнала обычного роутера (которого не нужно регистрировать) хватает в среднем на одну-две квартиры.»

**Comment by xN0D** [comment]
Да, конечно, но у меня почему то есть определенные сомнения, что узлы Medium охватывают площадь на "на одну-две квартиры".

**Comment by podivilov** [comment]
Тем не менее, мы не используем оборудование, которое подлежит обязательному лицензированию. Я администрирую несколько точек в Коломне и Озёрах, там стоят обычные микротики. Конечно, это не позволяет покрывать большую территорию, но это всяко лучше, чем совсем ничего.

**Comment by xN0D** [comment]
Обычные микротики могут выдавать до 1 Вт в зависимости от региональных установок, и я уверен что у вас там, в Коломне и Озёрах, не положенные 100 мВт (20дб), а намного больше. Но , к счастью, у нас с стране можно творить что угодно пока ты никому не мешаешь, или не обращаешь на себя внимание, так в данном случае и с Вашей сетью. Как только заявите о себе сколь нибудь серьезно, обязательно найдут нарушения, даже там где их нет. Это суровая действительность.

**Comment by podivilov** [comment]
К сожалению, вынужден с Вами согласиться. Но с РосКомСвободой мы в любом случае должны проконсультироваться. Praemonitus, praemunitus.

**Comment by dartraiden** [comment]
> А еще есть любопытный законопроект об авторизации WiFi

- это относится только к юрикам и ип, на физиков никаких обязанностей не налагается
- есть случаи, когда местный Роскомнадхор по скудоумию возбуждался на обычный домашний открытый Wi-Fi, но нет случаев, когда физику за это что-то было:
1) https://nag.ru/news/newsline/104537/roskomnadzor-trebuet-s-provaydera-lichnyie-dannyie-polzovatelya-chya-tochka-dostupa-wi-fi-okazalas-otkryitoy.html
пока неизвестно, чем кончится
2) мне известно о похожем случае, там, в итоге, натянули... провайдера. Вероятно, провайдер разорвёт договор с клиентом, из-за которого поимел проблемы, но и всё.

**Comment by podivilov** [comment]
@dartraiden, > определить провайдера затруднительно
Я бы даже сказал больше — определить провайдера невозможно. Конечно, если делать whois на отдельные IP в сети, то можно определить; но в I2P используется как чесночная, так и луковая маршрутизация — что пресекает на корню такую возможность.

**Comment by podivilov** [comment]
@dartraiden 
> есть случаи, когда местный Роскомнадхор по скудоумию возбуждался на обычный домашний открытый Wi-Fi

А не могли бы Вы привести подробности?

**Comment by dartraiden** [comment]
В качестве примера я дал ссылку, а второй пример надо искать. Там был клиент - обычное кафе, владелец которого, если мне не изменяет память, поменял DNS в свойствах подключения, а у провайдера блокировки как раз основывались на этом.

**Comment by podivilov** [comment]
В случае с I2P всё ещё более прозаично — если использовать только eepsites, которые поддерживают HTTPS (а это 7 уровень модели OSI), то и прикапываться будет не к чему — трафик-то шифрованный. К счастью, пока что 2048-кубитные квантовые компьютеры ещё не изобрели, поэтому можно особо не беспокоиться за то, что кто-то будет снифать трафик. Остаётся только приучить пользователей проверять самоподписанные сертификаты, как это делается с OpenPGP. Просто последние к этому привыкли, а для первых корпорации добра сделали гигантскую красную страницу со страшными буквами о том, что сертификат самоподписан.

**Comment by podivilov** [comment]
@xN0D 

В понедельник буду в офисе РосКомСвободы. Предложили провести консультацию pro bono. По результатам отпишусь здесь и, возомжно, опубликую статью на Хабре.

**Comment by xN0D** [comment]
@podivilov Есть ли новости? Очень интересно, что у Вас вышло с РосКомСвободой.

**Comment by podivilov** [comment]
@xN0D 

Вчера был в офисе РосКомСвободы, сейчас пишем письмо в Минкомсвязи.

Ответа, мне думается, придётся ждать нескоро, но по результатам я думаю опубликовать статью на Хабре.

Что касательно юридической точки зрения — РосКомСвобода не нашла никаких проблем с предоставлением услуг подвижной радиосвязи децентрализованным интернет-провайдером «Medium» на территории РФ. Теперь остаётся получить официальный ответ от Минкомсвязи, чтобы сообщество успокоилось.

**Comment by xN0D** [comment]
Вот это уже что то. Хотя по прежнему все очень смутно, но наблюдается поступательное движение.
Мне думается минкомсвязи все же найдет какие нибудь мелкие нарушения, но это будет лишь повод для адаптации сети к текущим условиям.


![1515321603_kamensk-lenin](https://user-images.githubusercontent.com/52774293/61269654-ef704480-a7a7-11e9-8e30-6c27d59ca581.jpg)

**Comment by podivilov** [comment]
Время покажет.

«Не стоит прогибаться под изменчивый мир, пусть лучше он прогнётся под нас».

**Comment by Eninspace** [comment]
29 Статья конституции РФ
Каждый имеет право свободно искать, получать, передавать, производить и распространять информацию любым законным способом.

Статья 19. Всеобщая декларация прав человека
Каждый человек имеет право на свободу убеждений и на свободное выражение их; это право включает свободу беспрепятственно придерживаться своих убеждений и свободу искать, получать и распространять информацию и идеи любыми средствами и независимо от государственных границ.

Вывод: передача информации посредством сети "Medium" полностью законна.

**Comment by xN0D** [comment]
Насколько я помню тайна переписки тоже есть в конституции, однако СОРМ, пакет Яровой...

**Comment by podivilov** [comment]
И опсосы, которые перевели сеть в Мск в режим GSM-only на выходных. С @xN0D солидарен.

**Comment by TheZavitaev** [comment]
Позвольте вставить свои пять копеек. Я в ИТ "простомимопроходил", однако мысль о том, что "я физлицо, поэтому никому ничего не должен" похожа на стрельбу по собственным коленям.
Например, есть Федеральный закон от 27.07.2006 N 149-ФЗ "Об информации, информационных технологиях и о защите информации". 
В ст. 5 Закона указано: информация может являться объектом публичных, гражданских и иных правовых отношений. Информация может свободно использоваться любым лицом и передаваться одним лицом другому лицу, если федеральными законами не установлены ограничения доступа к информации либо иные требования к порядку ее предоставления или распространения.
В ст. 6 говорится следующее: обладателем информации может быть гражданин (физическое лицо), юридическое лицо, Российская Федерация, субъект Российской Федерации, муниципальное образование.
Т.е. Закон №149-ФЗ распространяется на физлиц. И информация, передающаяся от юзера к юзеру попадает под этот закон.
Далее есть ст. 16: обладатель информации, оператор информационной системы в случаях, установленных законодательством Российской Федерации, обязаны обеспечить:
1) предотвращение несанкционированного доступа к информации и (или) передачи ее лицам, не имеющим права на доступ к информации;
2) своевременное обнаружение фактов несанкционированного доступа к информации;
3) предупреждение возможности неблагоприятных последствий нарушения порядка доступа к информации;
4) недопущение воздействия на технические средства обработки информации, в результате которого нарушается их функционирование;
5) возможность незамедлительного восстановления информации, модифицированной или уничтоженной вследствие несанкционированного доступа к ней;
6) постоянный контроль за обеспечением уровня защищенности информации;
7) нахождение на территории Российской Федерации баз данных информации, с использованием которых осуществляются сбор, запись, систематизация, накопление, хранение, уточнение (обновление, изменение), извлечение персональных данных граждан Российской Федерации.
За несоблюдение этих требований есть штраф по КоАП РФ (ст. 13.12). Для физлиц - это 500-1000 руб.
Дальше, я не до конца понял принцип работы сети, но если Вы получаете хоть что-то про физика (мыло, номер телефона, ФИО, etc). То тут уже включается закон о персональных данных (13.11 КоАП, 13.12 КоАП).
Да, для физиков маленькие штрафы, но у нас журналистам наркотики подкидывают, чтобы они всякое не писали...а тут пацаны сеть вне "Ока Саурона" подняли.

Допустим в ст. 10 Закона №149-ФЗ говорится о том, что передавать "запрещенку" нельзя. А если передается "запрещенка" с информацией, которая может "дестабилизировать ситуацию в стране", то это уже уголовка.

Например, [Дело нового величия](https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D0%BB%D0%BE_%C2%AB%D0%9D%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B8%D1%8F%C2%BB )
вот в Вашей сети завелись, например, такие партизаны. Что Вы будете делать? 

Или вспомним приложение Zello. PTP-рация для дальнобойщиков. Использовалась для координации протестных мероприятий против введения Протона - запретили. Если бы компания находилась физически у нас, допускаю, что кто-нибудь еще бы и присел.

**Comment by podivilov** [comment]
@TheZavitaev, добрый день!

Мы уже направили запорс в Минкомсвязи, чтобы понять, насколько это легально.

Там есть соответствующий пункт:

![](i.imgur.com/DeT2Olw.png)

**Comment by TheZavitaev** [comment]
@podivilov Добрый! Держите в курсе.

**Comment by podivilov** [comment]
@TheZavitaev обязательно. Я был в офисе Роскомсвободы, мы отдельно обсуждали этот пункт. Medium не попадает под ОРИ, так как он организует только передачу данных, их обработка не предусматривается. Вот если бы данные шли в открытом виде, то было бы другое дело. Но даже и тут много нюансов. В общем, будем ждать ответа.

**Comment by podivilov** [comment]
@TheZavitaev @xN0D, статья РосКомСвободы про Medium.

https://roskomsvoboda.org/49287/

**Comment by xN0D** [comment]
@podivilov, в этой статье нет ничего нового кроме маленькой оговорки Роскомсвободы о том, что они "...не обнаружили никаких проблем с безвозмездным предоставлением услуг подвижной радиосвязи..."
Слабая польза, очень слабая.

**Comment by podivilov** [comment]
@xN0D, до 13 сентября должен поступить официальный ответ от Минкомсвязи.

**Comment by xN0D** [comment]
Кстати, прямо вот сейчас мой внутренний параноик возможно родил способ дискредитировать сеть в целом. Что если сотрудники полиции или иже с ними, воспользуются инструкцией и построят свою medium сеть с бекждеком... Да да, я в курсе, информацию проходящую через их узлы не перехватить и не расшифровать, но такие узлы могут собирать кучу другой полезной для них информации. Время активности, место активности, mac адреса, возможно тип устройства и производитель, направление трафика и его объем. Создав mesh сеть с максимально малыми областями охвата и накрыв эти области банальным видеонаблюдением можно будет довольно просто деанонимизировать пеших и автопользователей. Со стационарными еще проще. Ну а дальше даже перехватывать ничего не нужно, банально подойдут и заберут телефон\ноут, и будут в нем искать интересующую их информацию.
Сейчас так делают с телеграмом, не спрашивая разрешения забирают телефон и ищут мессенджер, если находят, в лучшем случае будешь долго им объяснять для чего он тебе, и в подтверждении своих слов покажешь переписку.

**Comment by podivilov** [comment]
К сожалению, у нас не такие продвинутые товарищи сидят там, чтобы строить ещё один меш. Знаю по опыту общения с такими.

**Comment by l-n-s** [comment]
Грустный тред. Вместо того, чтобы развивать технологии, вы уже спрашиваете у власть имущих какое за это будет наказание. 

И даже если это не наказуемо, что им мешает позже принять запрещающий закон и осудить уже по факту? Вопрос риторический.

**Comment by podivilov** [comment]
@l-n-s, ну, почему же - "вместо того, чтобы развивать технологии"? Я в ближайшее время как минимум 8 точек собираюсь в Коломне поднять.

**Comment by l-n-s** [comment]
@podivilov ни в коем случае не умаляю заслуги. Я про это письмо минкомсвязи. Вот почему мы в своей стране должны так унижаться перед чиновниками, тратить своё время и силы? Даже при том, что это явным образом не зарегулировано.

**Comment by podivilov** [comment]
@l-n-s, ну, наше дело правое, просто народ запуган - и сам человек по природе своей слишком консервативен обычно, чтобы что-то менять. Народ боится власти. Бумажка - пусть бы даже и отписка - помогла бы привлечь большее количество людей к работе над проектом. Хотя, конечно, Вы правы - это в действительности ничем иным и не назовёшь, разве как унижением. Но делать нечего. Ждём ответа.

**Comment by xN0D** [comment]
@l-n-s, это банальное чувство самосохранения. Ввиду того, что все знают как работает наше законодательство(вот где уныние), не помешает лишний раз "переспросить". Лично мне проект нравится, я бы даже поучаствовал в нем, но я очень не хочу внезапно получить административку или уголовку, потому что этим проектом, кто то там стал воспользовался не по прямому своему назначению.

**Comment by podivilov** [comment]
@xN0D, а как эти гипотетические "они" вычислят, что кто-то использовал ресурсы сети не по назначению? У нас используется сквозное шифрование, мы даже от PKI отказались в пользу нативного шифрования Yggdrasil.

Это же не Tor. Тут нет проблем с входными и выходными нодами, всё E2E-encrypted.

![](https://hsto.org/webt/rt/lw/0i/rtlw0irzkmgcuk5mqor0mcvnk7w.png)

**Comment by xN0D** [comment]
Вот для этого и нужна "отписка", чтобы сам факт наличия сети не был наказуем, и чтобы любые действия одного любого пользователя сети medium не обременяли какой либо ответственностью остальных владельцев узлов сети. Когда станет на пальцах ясно, что не оштрафуют, и не посадят владельца узла за то, что его узлом воспользовался умалишенный/школьник/криминальный элемент и накачал литературы/торентов/запрешенного контента/сообщил о заложенной бомбе, тогда сеть расцветет буйным цветом. Сейчас все неравнодушные выжидают как все пойдет в правовом поле. Все читают/смотрят интернет/СМИ, все видят как на пустом месте себе можно нажить проблем. Время не простое, лишние проблемы никому не нужны.

**Comment by podivilov** [comment]
@xN0D, у нас конституция уже с завидным постоянством нарушается, о чём Вы?

**Comment by podivilov** [comment]
Обсуждения переехали на [discuss.mediumfoundation.org](https://discuss.mediumfoundation.org/).
