### ISSUE TITLE
I2P + Yggdrasil

### ISSUE THREAD

**Issue by whoizit** [medium-isp/medium#2]
Я автор чата по mesh-сетям в Telegram (MATRIX, XMPP, IRC) [`@meshnet`](http://t.me/meshnet) (https://github.com/russian-meshnet), который входит в крупное сообщество [`@distributed`](http://t.me/distributed)

Я хочу спросить, а знаете ли вы об [yggdrasil](https://yggdrasil-network.github.io)? 
Просто вы написали так, что вы не нашли соседей с мешем и по этому вы переключились на _I2P_. Мне кажется тут вы ошиблись. В современных mesh-сетях вроде _cjdns_/_yggdrasil_ есть режим _friend2friend_ (_f2f_), когда вы, не имея соседа с mesh-нодой, можете линковаться к другим нодам через интернет. И мы это активно используем, пока не имеем соседей с мешем.

У нас есть ресурсы, в том числе прокси в интернет. Да это не I2P где всё анонимно и ресурсов на порядки больше. Но Yggdrasil очень молод и в отличии от I2P - очень быстрый. Имеет режимы full и partial mesh. А в режиме full-mesh так-же является анонимным 
[Список публичных пиров](https://github.com/yggdrasil-network/public-peers)

**Comment by podivilov** [comment]
Добрый день, @whoizit!

Да, об yggdrasil я знаю непонаслышке — перед тем, как запустить кампанию Медиума, я достаточно подробно изучил тему Mesh-сетей.

Цель Медиума — не создать Mesh-сеть, а повысить количество транзитных I2P узлов и осведомлённость людей в принципе об этой сети. Подключиться по Wi-Fi к I2P и использовать её ресурсы всяко проще, чем заморачиваться с настройкой роутера.

**Comment by Scondo** [comment]
С практической точки зрения можно совместить... ну это будет такой "продвинутый" вариант, допустим.
1) Добавить yggdrasil как дополнительный функционал точки доступа
2) Точка доступа при этом будет как транзитным узлом I2P, так и транзитным узлом yggdrasil
3) Можно настроить PAC - скрипт указывающий на использование I2P узла оператора для I2P, тогда yggdrasil будет частично заменять сомой традиционный стек IP, паралельно решая вопрос шифрования клиент-прокси.

**Comment by podivilov** [comment]
@Scondo, хотелось бы услышать от Вас комментарии касательно добавления Yggdrasil в качестве дополнительного функционала точки доступа. Вы предлагаете для этого создавать ещё одну радиоточку с отличным от первой идентификатором (SSID)? Или же проксировать соединения для доменов .i2p в сеть I2P, а с Yggdrasil поступить как-то иначе? Какие есть мысли на этот счёт?

**Comment by podivilov** [comment]
Кстати, I2P имеет возможность работы в режиме, совместимом с Mesh-сетями. Это бы тоже было бы здорово обмозговать.

**Comment by podivilov** [comment]
@whoizit, перешли на Yggdrasil.
