### ISSUE TITLE
Сервис: почта

### ISSUE THREAD

**Issue by podivilov** [medium-isp/medium#22]
Проводится закрытое тестирование сервиса [mail.medium.i2p](http://mail.medium.i2p/?i2paddresshelper=MJcd4jvQLqCmBPJLMMMckL3tTAz2Lq4qUQfSqogRO15oAn2H0mHRGhTdDZcYvw-UCZVGzDBYfcxwuKRZfuaseklFk50KX7U1VELavWIryVXDTzTjW0DDeuJcQTgBdf9IowCi7AII5Q~0dPEJVQQ1q2o7aV7SjYrMMHTfkhnD3G0qrwnIkztztZ-rmyt2baJN1ORf9nDfwrq1uVKhEp60rI4rMHmnZSYejnawbvJMWjqn5tYtNCrUq~i3rEDTIbF1zDytveqXbIc8a~g8K9oRNlWtZJNfzSncpVeZGHUxn-btvC7xszM4lO5HCUwB7mwPnGy6AFZ6Cw0Vl0f-qJWQ1jPMIy9oTECcssvkKrf0vSNIUWTq6XHa2kPdOA881~iS2NEmLdRCK5kcZfD1l~-TLW-vWU1JYvXJcK1DpIiWT-mKpQSSl4L9azJ3hwVa9Y-EYM4x8mrS5gEiJEmeG~4Kceqw3lNKE7KyWV3NqGO6acm8Uq7vJ3DRCjQmULxCYag5BQAEAAcAAA==). По всем вопросам обращаться на mihail@podivilov.ru.

**Comment by user2kcd** [comment]
А mail.medium.isp?

**Comment by podivilov** [comment]
@user2kcd, так закрыто же.
