### ISSUE TITLE
Текущее состояние точек сети «Medium»

### ISSUE THREAD

**Issue by podivilov** [medium-isp/medium#3]
Формат оформления сообщения:

[код региона].[название города (латиницей)].[номер точки по списку]

Перед публикацией сообщения убедитесь в том, что точка уже есть в [списке](https://github.com/medium-isp/medium/tree/master/ru).

Например: Точка **63.samara.1** недоступна или Точка **50.kolomna.2** снова доступна.

**Comment by LainTech** [comment]
Было бы неплохо собирать все точки на сервисе вроде https://www.google.com/mymaps или аналогичном.

**Comment by podivilov** [comment]
@LainTech, создайте новый Issue.

**Comment by podivilov** [comment]
@LainTech https://github.com/medium-isp/medium/issues/6

**Comment by Eninspace** [comment]
Есть ещё https://www.openstreetmap.org

**Comment by podivilov** [comment]
Точки обновляются в автоматическом режиме.
