### ISSUE TITLE
Адресация в medium

### ISSUE THREAD

**Issue by ne-vlezay80** [medium-isp/medium#35]
Какой диапазон адресов используется в этой сети при примом подключении?

**Comment by podivilov** [comment]
@ne-vlezay80, 200::/7.

**Comment by ne-vlezay80** [comment]
А если к medium подключаться через wifi? Но, я как понял, для подключения к сети даже через wifi нужно устанавливать клиент yggdrasil?

**Comment by podivilov** [comment]
@ne-vlezay80 Medium работает на уровне L2, Yggdrasil на уровне L3. Соответственно, для подключения к Medium необходимо осуществить подключение на уровне L2 через Wi-Fi, а затем на уровне L3 посредством использования клиента Yggdrasil.
