### ISSUE TITLE
Привлечение операторов

### ISSUE THREAD

**Issue by poststatist** [medium-isp/medium#36]
В настоящее время, люди абсолютно лишены мотивации становиться операторами сети: мало того, что это не приносит им никакой выгоды, так еще и несет определенные риски. 
Нужно решить эту проблему и привлечь операторов как минимум одной точки доступа в каждом регионе РФ.

**Comment by podivilov** [comment]
Может быть, городе, а не регионе?

**Comment by podivilov** [comment]
Обсуждения переехали на [discuss.mediumfoundation.org](https://discuss.mediumfoundation.org/)
